services:
  hyperion:
    build: .
    image: hyperion-starter-hyperion
    env_file:
      - path: .env
        required: false
    ports:
      - "8000:8000"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    restart: unless-stopped
