import asyncio
import json
import logging

from fastapi import FastAPI
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import StreamingResponse
from pydantic import BaseModel, Field

from hyperion import actions
from hyperion.agent import Hyperion

logging.basicConfig(level=logging.INFO)
log = logging.getLogger("hyperion")

app = FastAPI(title="Hyperion Agent")

# The IDE frontend calls this service straight from the browser: CORS must stay enabled.
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

REQUEST_TIMEOUT = 240  # seconds for one whole reply
agent = Hyperion()


class ChatRequest(BaseModel):
    user_id: str = Field(min_length=1, max_length=200)  # a UUID generated by the IDE - the session key
    text: str  # the text the user typed in the chat


async def generate_reply(request: ChatRequest):
    try:
        async with asyncio.timeout(REQUEST_TIMEOUT):
            async for frame in agent.chat(request.user_id, request.text):
                yield frame
    except TimeoutError:
        yield actions.text("\nThat took too long, so I stopped. Nothing further was changed - please try again.")
    except Exception:  # pragma: no cover - agent.chat already guards; this keeps the SSE stream well-formed
        log.exception("unhandled error in /chat")
        yield actions.text("\nSorry, something went wrong. Nothing was changed.")
    yield actions.DONE


@app.post("/chat")
async def chat(request: ChatRequest):
    return StreamingResponse(
        generate_reply(request),
        media_type="text/event-stream",
        headers={"Cache-Control": "no-cache", "X-Accel-Buffering": "no", "Connection": "keep-alive"},
    )


@app.get("/health")
async def health():
    return {"status": "ok"}


if __name__ == "__main__":
    import uvicorn

    uvicorn.run(app, host="0.0.0.0", port=8000)
