"""Deterministic generators for common 'create a file' requests (reliable even with a small LLM)."""

from __future__ import annotations

import re

from .analyzer.common import KNOWN_TAGS, image_base, split_image

DEFAULT_PORTS = {"nginx": 80, "httpd": 80, "redis": 6379, "postgres": 5432, "mysql": 3306, "mongo": 27017,
                 "eclipse-mosquitto": 1883, "rabbitmq": 5672, "memcached": 11211}
# Official images that run as root by default; runAsNonRoot would make them crash, so we omit it.
ROOT_IMAGES = {"nginx", "httpd", "redis", "postgres", "mysql", "mongo", "rabbitmq", "memcached"}


def slug(s: str) -> str:
    return re.sub(r"[^a-z0-9-]+", "-", s.lower()).strip("-")[:50] or "app"


def k8s_deployment(image: str, name: str | None = None, port: int | None = None, replicas: int = 1) -> str:
    img_name, tag = split_image(image)
    base = image_base(img_name)
    if tag in (None, "latest"):
        tag = KNOWN_TAGS.get(base, "latest" if base not in KNOWN_TAGS else KNOWN_TAGS[base])
        if tag == "latest":
            tag = None
    ref = f"{img_name}:{tag}" if tag else img_name
    name = slug(name or base)
    port = port or DEFAULT_PORTS.get(base, 8080)
    sec = "" if base in ROOT_IMAGES else (
        "          securityContext:\n            runAsNonRoot: true\n            runAsUser: 10001\n"
        "            allowPrivilegeEscalation: false\n")
    return f"""# Generated by Hyperion - edge-friendly defaults: pinned image, resource requests/limits, probes
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {name}
  labels:
    app: {name}
spec:
  replicas: {replicas}
  selector:
    matchLabels:
      app: {name}
  template:
    metadata:
      labels:
        app: {name}
    spec:
      containers:
        - name: {name}
          image: {ref}
          ports:
            - containerPort: {port}
          resources:
            requests:
              cpu: 100m
              memory: 128Mi
            limits:
              cpu: 500m
              memory: 256Mi
          readinessProbe:
            tcpSocket:
              port: {port}
            initialDelaySeconds: 5
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: {port}
            initialDelaySeconds: 15
            periodSeconds: 10
{sec}"""


def compose_file(image: str, name: str | None = None, port: int | None = None) -> str:
    img_name, tag = split_image(image)
    base = image_base(img_name)
    if tag in (None, "latest") and base in KNOWN_TAGS:
        tag = KNOWN_TAGS[base]
    ref = f"{img_name}:{tag}" if tag and tag != "latest" else img_name
    name = slug(name or base)
    port = port or DEFAULT_PORTS.get(base, 8080)
    return f"""# Generated by Hyperion
services:
  {name}:
    image: {ref}
    restart: unless-stopped
    ports:
      - "{port}:{port}"
    deploy:
      resources:
        limits:
          cpus: "0.5"
          memory: 256M
    healthcheck:
      test: ["CMD-SHELL", "exit 0"]  # TODO: replace with a real probe for your service
      interval: 30s
      timeout: 5s
      retries: 3
"""
