"""Orchestrates all rule modules over a workspace snapshot and scores the result."""

from __future__ import annotations

import posixpath

from ..models import Finding, Report, SEVERITIES, compute_score, MANUAL_ONLY, SAFE_AUTO
from .common import mk
from ..workspace import Snapshot
from . import rules_compose, rules_config, rules_deps, rules_docker, rules_k8s, rules_profile
from .common import kind_of_file, is_map, load_yaml_docs

APP_MANIFESTS = {"requirements.txt", "package.json", "pyproject.toml", "go.mod", "pom.xml", "Cargo.toml"}

DOCKERIGNORE_TEXT = """# Generated by Hyperion Sentinel - keeps the build context small and free of secrets
.git
.gitignore
.env
.env.*
!.env.example
__pycache__/
*.py[cod]
.venv/
venv/
node_modules/
.pytest_cache/
.idea/
.vscode/
*.log
Dockerfile*
docker-compose*.y*ml
README.md
"""

GOOD_MESSAGES = {
    ("dockerfile", "DF-LATEST"): "Dockerfile base images are pinned",
    ("dockerfile", "DF-ROOT"): "Dockerfile runs as a non-root user",
    ("dockerfile", "DF-HEALTHCHECK"): "Dockerfile defines a HEALTHCHECK",
    ("k8s", "K8S-RESOURCES"): "Kubernetes containers declare resource requests and limits",
    ("k8s", "K8S-READINESS"): "Kubernetes containers have readiness probes",
    ("k8s", "K8S-LATEST"): "Kubernetes images are pinned",
    ("k8s", "K8S-NONROOT"): "Kubernetes workloads run as non-root",
    ("compose", "CMP-RESTART"): "Compose services declare a restart policy",
    ("compose", "CMP-RESOURCES"): "Compose services declare resource limits",
    ("profile", "PROF-LATEST"): "HYPER-AI profile images are pinned",
}


def _order(f: Finding):
    return (SEVERITIES.index(f.severity), f.file, f.line or 0)


async def analyze_workspace(snap: Snapshot, validate=None) -> Report:
    findings: list[Finding] = []
    seen_kinds: set[str] = set()
    files = snap.files
    inspected: list[str] = []

    for path in sorted(files):
        content = files[path]
        kind = kind_of_file(path)
        relevant = False
        try:
            if kind == "dockerfile":
                findings += rules_docker.analyze_dockerfile(path, content)
                seen_kinds.add("dockerfile"); relevant = True
            elif kind in ("yaml", "compose"):
                docs, err = load_yaml_docs(content)
                if err:
                    line, msg = err
                    findings.append(mk("CFG-MALFORMED", "HIGH", "configuration", path, "YAML cannot be parsed",
                                       f"{'line ' + str(line) + ': ' if line else ''}{msg[:160]}",
                                       "Tools cannot read or deploy a malformed file, and it cannot be analysed further.",
                                       "Fix the YAML syntax.", MANUAL_ONLY, line=line))
                    relevant = True
                for i, d in enumerate(docs):
                    if not is_map(d):
                        continue
                    pk = rules_profile.detect_profile(d)
                    if kind == "compose" and "services" in d:
                        findings += rules_compose.analyze_compose(path, d); seen_kinds.add("compose"); relevant = True
                    elif pk:
                        findings += rules_profile.analyze_profile(path, d, pk); seen_kinds.add("profile"); relevant = True
                        if validate is not None and i == 0:
                            findings += rules_profile.validation_findings(path, await validate(path))
                    elif "services" in d and "kind" not in d:
                        findings += rules_compose.analyze_compose(path, d); seen_kinds.add("compose"); relevant = True
                    elif "kind" in d and "apiVersion" in d:
                        r = rules_k8s.analyze_k8s_doc(path, d, i)
                        findings += r; seen_kinds.add("k8s"); relevant = True
            elif kind == "requirements":
                findings += rules_deps.analyze_requirements(path, content); relevant = True; seen_kinds.add("deps")
            elif kind == "package_json":
                findings += rules_deps.analyze_package_json(path, content); relevant = True; seen_kinds.add("deps")
            if kind not in ("dockerfile", "compose"):
                sec = rules_config.analyze_secrets(path, content)
            else:
                sec = rules_config.analyze_secrets(path, content)  # tokens only; assignment patterns skipped for these kinds
            if sec:
                findings += sec
            if relevant or kind == "env":
                inspected.append(path)
        except Exception as exc:  # a rule bug must never crash the agent
            findings.append(mk("CFG-ANALYZER-ERROR", "LOW", "configuration", path, "File could not be fully analysed",
                               f"{type(exc).__name__}: {str(exc)[:100]}", "An unexpected format prevented some checks.",
                               "Review this file manually.", MANUAL_ONLY))

    findings += rules_config.analyze_urls(files)
    findings += rules_config.analyze_env_template(files)
    findings += _completeness(files, seen_kinds)

    # Dedupe identical (rule,file,line,target) hits
    uniq: dict[tuple, Finding] = {}
    for f in findings:
        uniq.setdefault((f.rule, f.file, f.line, f.fix.get("target"), f.evidence), f)
    findings = sorted(uniq.values(), key=_order)

    rules_hit = {(k, f.rule) for f in findings for k in ("dockerfile", "k8s", "compose", "profile")}
    good = []
    for (kind, rule), msg in GOOD_MESSAGES.items():
        if kind in seen_kinds and not any(f.rule == rule for f in findings):
            good.append(Finding(rule=rule.replace("-", "-OK-", 1), severity="GOOD", category=kind, file="",
                                finding=msg, evidence="", why_it_matters="", recommended_fix=""))
    inspected = sorted(set(inspected) | {p for p in files if kind_of_file(p) in ("dockerfile", "compose", "dockerignore")})
    return Report(score=compute_score(findings), findings=findings, good=good, files_inspected=inspected, skipped=snap.skipped)


def _completeness(files: dict[str, str], seen: set[str]) -> list[Finding]:
    out = []
    names = {posixpath.basename(p) for p in files}
    folders = {posixpath.dirname(p) for p in files}
    for p in sorted(files):
        if kind_of_file(p) == "dockerfile":
            folder = posixpath.dirname(p)
            if posixpath.join(folder, ".dockerignore") not in files:
                out.append(mk("DF-DOCKERIGNORE", "LOW", "project", p, "No .dockerignore next to the Dockerfile",
                              f"{posixpath.join(folder, '.dockerignore')} not found",
                              "Without it the build context can include .git, .env and caches - slower builds, larger images, leaked secrets.",
                              "Create a .dockerignore.", SAFE_AUTO, target=folder, folder=folder))
    has_df = any(kind_of_file(p) == "dockerfile" for p in files)
    has_app = bool(names & APP_MANIFESTS) or any(p.endswith((".py", ".js", ".ts", ".go")) for p in files)
    if has_app and not has_df:
        out.append(mk("PRJ-NO-DOCKERFILE", "MEDIUM", "project", "(workspace)", "Application code present but no Dockerfile",
                      "No Dockerfile found", "There is no defined way to build a portable image to ship to edge nodes.",
                      "Add a Dockerfile.", MANUAL_ONLY))
    if has_df and not ({"k8s", "compose", "profile"} & seen):
        out.append(mk("PRJ-NO-DEPLOY", "MEDIUM", "project", "(workspace)", "Dockerfile present but no deployment manifest",
                      "No Kubernetes, Compose or HYPER-AI profile found", "The image has no declared way to be deployed, sized or exposed.",
                      "Add a deployment manifest or HYPER-AI application profile.", MANUAL_ONLY))
    if has_app and "README.md" not in names and "readme.md" not in {n.lower() for n in names}:
        out.append(mk("PRJ-NO-README", "LOW", "project", "(workspace)", "No README",
                      "No README file found", "Nobody can tell how to configure and run the app.", "Add a README.", MANUAL_ONLY))
    if any(p.endswith(".py") for p in files) and not (names & {"requirements.txt", "pyproject.toml", "Pipfile"}):
        out.append(mk("PRJ-NO-DEPS", "LOW", "project", "(workspace)", "Python code but no dependency manifest",
                      "No requirements.txt / pyproject.toml", "Builds cannot reproduce the runtime environment.",
                      "Add requirements.txt with pinned versions.", MANUAL_ONLY))
    return out
